FROM alpine:3.8

MAINTAINER tmervin@student.42.fr

RUN apk update
RUN apk upgrade
RUN apk add vim

ENTRYPOINT vim

# Build Dockerfile
# docker build --tag ex00 .

# Run Dockerfile
# docker run -it --rm ex00 .

# List images
# docker images